apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-study-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-study-service
  template:
    metadata:
      labels:
        app: cicd-study-service
    spec:
      containers:
        - name: app
          image: ghcr.io/matcha2smiley/cicd-study-service:8c1dbe4f47da43e5d339f79fb017deac3253dec4
          ports:
            - containerPort: 8080
